# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
title: Queer Code
description: We are a community of queer coders. We build tech together, share our ideas at local meetups, and provide support for queer people working in software development.
sass:
    sass_dir: _sass
    style: compressed
